# Generated by Django 5.2.4 on 2025-07-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0002_blockedip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestlog',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='requestlog',
            name='path',
        ),
        migrations.RemoveField(
            model_name='requestlog',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='requestlog',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
